name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: pre-build
      run: ./autogen.sh
    - name: configure
      run: ./configure
    - name: build binary
      run: make dist
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
