name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: aclocal
      run: aclocal
    - name: autoconf
      run: autoconf
    - name: automake
      run: automake --add-missing
    - name: make dist
      run: make dist
    - name: make check
      run: make check
    - name: make distcheck
      run: make distcheck
